[package]
name = "weather-cli"
version = "0.1.0"
authors = ["Steven Anderson <steven.a.anderson2012@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
